### ISSUE TITLE
spacing

### ISSUE THREAD

**Issue by dackdel** [jonjon1251/LaughingMan#1]
the spacing in the text should be a lot more :) it feels like you are a copy of the laughing man with the way your logo looks.

**Comment by jonjon1251** [comment]
Do you mean the spacing should be closer together ?

**Comment by dackdel** [comment]
the top edge of the text and the inner line of the edge of the circle. also i think the colour is a bit off. hex code:23498c maybe or RGB (13.7, 28.6, 54.9). 
![46709078-e50c9300-cbf6-11e8-9076-90217a556f3f](https://user-images.githubusercontent.com/380951/46966007-09baac00-d0ca-11e8-9cd5-ee267246f924.PNG)
and heres the original i think 
![300](https://user-images.githubusercontent.com/380951/46966014-13441400-d0ca-11e8-92ff-5d82963ce8a6.png)
also i found the guy who actually designed the logo for the show, found him on tumblr and he replied. im sure he would reply to you as well. http://number3-design.tumblr.com/

**Comment by dackdel** [comment]
![unknown-51](https://user-images.githubusercontent.com/380951/46966444-6b2f4a80-d0cb-11e8-8ccc-6afaa891a28d.jpg)
